[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "Go to /"

[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd /run/media/$USER"
desc = "Go to removable [m]edia"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/dev"
desc = "Go to ~/dev"

[[mgr.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Downloads"
desc = "Go to downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/images/screenshots"
desc = "Go to screenshots"
