[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "Go to /"

[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd /run/media/$USER"
desc = "Go to removable [m]edia"

[[mgr.prepend_keymap]]
on   = [ "g", "G" ]
run  = "cd ~/Git"
desc = "Go to ~/Git"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/Pictures/screenshots"
desc = "Go to screenshots"
