[flavor]
dark = "tokyo-night"

[indicator]
padding = { open = "█", close = "█" }

[icon]
prepend_dirs = [
  { name = ".cache", text = ""},
  { name = ".config", text = "" },
  { name = ".dotfiles", text = ""},
  { name = ".gnupg", text = "󰌆" },
  { name = ".ssh", text = ""},
  { name = "apps", text = ""},
  { name = "dev", text = "" },
  { name = "docs", text = "" },
  { name = "img", text = "" },
  { name = "Trash", text = ""}
]
